export const POPULATE_POKEMON_SELECTOR = "POPULATE_POKEMON_SELECTOR";
export const DISPLAY_SIZE_IS_LARGE = "DISPLAY_SIZE_IS_LARGE";
export const DISPLAY_SIZE_NOT_LARGE = "DISPLAY_SIZE_NOT_LARGE";
export const SELECT_POKEMON = "SELECT_POKEMON";
export const UPDATE_SEARCHFIELD = "UPDATE_SEARCHFIELD";
